// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

// Admin is the golang structure for table admin.
type Admin internal.Admin

// Fill with you ideas below.
