// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

// GroupBill is the golang structure for table group_bill.
type GroupBill internal.GroupBill

// Fill with you ideas below.
