// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

// Group is the golang structure for table group.
type Group internal.Group

// Fill with you ideas below.

//UserGroupStatRep 我的团队统计
type UserGroupStatRep struct {
	UserCnt uint `json:"userCnt"` //团队人数
	Days    uint `json:"days"`    //待付款累计天数
}

//UserGroupListRep 我的团队详情列表
type UserGroupListRep struct {
	Name string `json:"name"` //名称
	Days uint   `json:"days"` //使用天数
}

// GroupListAdminReq 管理列表请求数据
type GroupListAdminReq struct {
	Page
	Keywords string `json:"keywords"`
}
