// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

// GroupDailyStat is the golang structure for table group_daily_stat.
type GroupDailyStat internal.GroupDailyStat

// Fill with you ideas below.
