// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

// MessageRead is the golang structure for table message_read.
type MessageRead internal.MessageRead

// Fill with you ideas below.
