// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

// Refund is the golang structure for table refund.
type Refund internal.Refund

// Fill with you ideas below.
