// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
    "battery/app/model/internal"
)

const (
    ShopStateOpen  = 1
    ShopStateClose = 2
)

// Shop is the golang structure for table shop.
type Shop internal.Shop

// ShopManagerChangeStateReq 门店修改门店状态请求
type ShopManagerChangeStateReq struct {
    State uint `validate:"required" v:"required|in:1,2"` // 门店状态 1 营业中 2 休息中
}

// ShopListUserReq 骑手获取门店列表请求
type ShopListUserReq struct {
    Page
    Lng    float64 `validate:"required" json:"lng"`
    Lat    float64 `validate:"required" json:"lat"`
    CityId uint64  `validate:"required" json:"cityId"`
    Name   string  `json:"name"` // 门店名称。搜索时使用
}

// ShopListAdminReq 管理员获取门店列表请求
type ShopListAdminReq struct {
    Page
    Name string `json:"name"` // 门店名称, 搜索时使用
}

// ShopListUserRep 骑手获取门店列表响应
type ShopListUserRep struct {
    Id           uint     `validate:"required" json:"id"`           // ID
    Img          string   `validate:"required" json:"img"`          // 图片
    Tags         []string `validate:"required" json:"tags"`         // 标签
    Name         string   `validate:"required" json:"name"`         // 名称
    Lng          float64  `validate:"required" json:"lng"`          // 经度
    Lat          float64  `validate:"required" json:"lat"`          // 纬度
    BatteryTotal uint     `validate:"required" json:"batteryTotal"` // 备货
    Distance     uint     `validate:"required" json:"distance"`     // 距离
    Mobile       string   `validate:"required" json:"mobile"`       // 联系手机号码
    Address      string   `validate:"required" json:"address"`      // 详细地址
    State        uint     `validate:"required" json:"state"`        // 门店状态 1 营业中 2 休息中
}

type ShopListItem struct {
    Id              uint   `json:"id"`
    Name            string `json:"name"`            // 门店名称
    State           uint   `json:"state"`           // 门店状态 0 休息中，1 营业中，2 外出中
    DistrictId      uint   `json:"districtId"`      // 区县ID
    CityId          uint   `json:"cityId"`          // 城市ID
    ProvinceId      uint   `json:"provinceId"`      // 省份ID
    ManagerName     string `json:"managerName"`     // 管理员姓名
    Mobile          string `json:"mobile" `         // 管理员电话
    BatteryInCnt60  uint   `json:"batteryInCnt60"`  // 60伏电池入库数量
    BatteryInCnt72  uint   `json:"batteryInCnt72"`  // 72伏电池入库数量
    BatteryOutCnt60 uint   `json:"batteryOutCnt60"` // 60伏电池出库数量
    BatteryOutCnt72 uint   `json:"batteryOutCnt72"` // 72伏电池出库数量
    BatteryCnt60    int    `json:"batteryCnt60"`    // 60伏电池数量
    BatteryCnt72    int    `json:"batteryCnt72"`    // 72伏电池数量
    ChargerCnt      int    `json:"chargerCnt"`      // 充电器数量
    ExceptionCnt    int    `json:"exceptionCnt"`    // 异常数量
}

// ShopDetail 门店详情
type ShopDetail struct {
    Name        string  `json:"name"  v:"required"`                      // 门店名称
    State       uint    `json:"state" v:"required|in:1,2"`               // 初始状态
    ManagerName string  `json:"managerName" v:"required"`                // 管理员
    Mobile      string  `json:"mobile" v:"required|phone-loose"`         // 手机号
    V60         int     `json:"v60" v:"required|integer|between:1,9999"` // 60伏电池入库数量
    V72         int     `json:"v72" v:"required|integer|between:1,9999"` // 72伏电池入库数量
    ProvinceId  uint    `json:"provinceId" v:"required|integer|min:1"`   // 省份ID
    CityId      uint    `json:"cityId" v:"required|integer|min:1"`       // 城市ID
    DistrictId  uint    `json:"districtId" v:"required|integer|min:1"`   // 区县ID
    Address     string  `json:"address" v:"required"`                    // 详细地址
    Lng         float64 `json:"lng" v:"required"`                        // 经度
    Lat         float64 `json:"lat" v:"required"`                        // 纬度
}

// ModifyShopReq 编辑门店
type ModifyShopReq struct {
    Name        string  `json:"name"  v:"required"`
    State       uint    `json:"state" v:"required|in:1,2"`
    ManagerName string  `json:"managerName" v:"required"`
    Mobile      string  `json:"mobile" v:"required|phone-loose"`
    ProvinceId  uint    `json:"provinceId" v:"required|integer|min:1"`
    CityId      uint    `json:"cityId" v:"required|integer|min:1"`
    DistrictId  uint    `json:"districtId" v:"required|integer|min:1"`
    Address     string  `json:"address" v:"required"`
    Lng         float64 `json:"lng" v:"required"`
    Lat         float64 `json:"lat" v:"required"`
}

// ShopIdNameList ID Name 列表
type ShopIdNameList struct {
    Id   uint   `json:"id"`
    Name string `json:"name"`
}
