// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

const (
	ShopStateOpen  = 1
	ShopStateClose = 2
)

// Shop is the golang structure for table shop.
type Shop internal.Shop

// ShopManagerChangeStateReq 店长修改店铺状态请求
type ShopManagerChangeStateReq struct {
	State uint `validate:"required" v:"required|in:1,2"` //店铺状态 1 营业中 2 休息中
}

// ShopListUserReq 骑手获取店铺列表请求
type ShopListUserReq struct {
	Page
	Lng    float64 `validate:"required" json:"lng"`
	Lat    float64 `validate:"required" json:"lat"`
	CityId uint64  `validate:"required" json:"cityId"`
	Name   string  `json:"name"` //店铺名称。搜索时使用
}

// ShopListAdminReq 管理员获取店铺列表请求
type ShopListAdminReq struct {
	Page
	Name string `json:"name"` //店铺名称。搜索时使用
}

// ShopListUserRep 骑手获取店铺列表响应
type ShopListUserRep struct {
	Id           uint     `validate:"required" json:"id"`           //ID
	Img          string   `validate:"required" json:"img"`          //图片
	Tags         []string `validate:"required" json:"tags"`         //标签
	Name         string   `validate:"required" json:"name"`         //名称
	Lng          float64  `validate:"required" json:"lng"`          //经度
	Lat          float64  `validate:"required" json:"lat"`          //纬度
	BatteryTotal uint     `validate:"required" json:"batteryTotal"` //备货
	Distance     uint     `validate:"required" json:"distance"`     //距离
	Mobile       string   `validate:"required" json:"mobile"`       //联系手机号码
	Address      string   `validate:"required" json:"address"`      //详细地址
	State        uint     `validate:"required" json:"state"`        //店铺状态 1 营业中 2 休息中
}
