// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

// SysPermissions is the golang structure for table sys_permissions.
type SysPermissions internal.SysPermissions

// Fill with you ideas below.
