// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"battery/app/model/internal"
)

// SysRoles is the golang structure for table sys_roles.
type SysRoles internal.SysRoles

// Fill with you ideas below.
