// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Admin is the golang structure for table admin.
type Admin struct {
	Id        uint        `orm:"id,primary" json:"id"`        //
	CreatedAt *gtime.Time `orm:"createdAt"  json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updatedAt"  json:"updatedAt"` //
	Username  string      `orm:"username"   json:"username"`  //
	Passwrod  string      `orm:"passwrod"   json:"passwrod"`  //
	Salt      string      `orm:"salt"       json:"salt"`      //
}
