// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// Districts is the golang structure for table districts.
type Districts struct {
	Id       uint    `orm:"id,primary" json:"id"`       //
	ParentId uint    `orm:"parentId"   json:"parentId"` //
	AdCode   uint    `orm:"adCode"     json:"adCode"`   //
	CityCode string  `orm:"cityCode"   json:"cityCode"` //
	Name     string  `orm:"name"       json:"name"`     //
	Level    string  `orm:"level"      json:"level"`    //
	Lng      float64 `orm:"lng"        json:"lng"`      //
	Lat      float64 `orm:"lat"        json:"lat"`      //
}
