// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// GroupDailyStat is the golang structure for table group_daily_stat.
type GroupDailyStat struct {
	Id          uint64      `orm:"id,primary"  json:"id"`          //
	GroupId     uint        `orm:"groupId"     json:"groupId"`     //
	BatteryType uint        `orm:"batteryType" json:"batteryType"` // 电池型号 60 / 72
	IsArrears   uint        `orm:"isArrears"   json:"isArrears"`   // 是否未付款 1 是 0 不是
	Date        uint        `orm:"date"        json:"date"`        // 日期 如 20210705
	Total       uint        `orm:"total"       json:"total"`       // 使用人数
	CreatedAt   *gtime.Time `orm:"createdAt"   json:"createdAt"`   // 创建时间
	UpdatedAt   *gtime.Time `orm:"updatedAt"   json:"updatedAt"`   //
}
