// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// GroupUser is the golang structure for table group_user.
type GroupUser struct {
	Id        uint        `orm:"id,primary" json:"id"`        //
	GroupId   uint        `orm:"groupId"    json:"groupId"`   // 团队ID
	UserId    uint64      `orm:"userId"     json:"userId"`    // 用户ID
	DeletedAt *gtime.Time `orm:"deletedAt"  json:"deletedAt"` // 注销时间
	CreatedAt *gtime.Time `orm:"createdAt"  json:"createdAt"` //
	UpdatedAt *gtime.Time `orm:"updatedAt"  json:"updatedAt"` //
}
