// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Group is the golang structure for table group.
type Group struct {
	Id            uint        `orm:"id,primary"    json:"id"`            //
	Name          string      `orm:"name"          json:"name"`          // 名称
	ProvinceId    uint        `orm:"provinceId"    json:"provinceId"`    //
	CityId        uint        `orm:"cityId"        json:"cityId"`        //
	ContractFile  string      `orm:"contractFile"  json:"contractFile"`  // 合同文件
	ContactName   string      `orm:"contactName"   json:"contactName"`   //
	ContactMobile string      `orm:"contactMobile" json:"contactMobile"` //
	CreatedAt     *gtime.Time `orm:"createdAt"     json:"createdAt"`     //
	UpdatedAt     *gtime.Time `orm:"updatedAt"     json:"updatedAt"`     //
}
