// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

// GroupBill is the golang structure for table group_bill.
type GroupBill struct {
	Id uint64 `orm:"id,primary" json:"id"` //
}
