// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Message is the golang structure for table message.
type Message struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	Type      uint        `orm:"type"       json:"type"`      //
	UserId    uint64      `orm:"userId"     json:"userId"`    // 0 标识推送所有用户
	Title     string      `orm:"title"      json:"title"`     //
	Summary   string      `orm:"summary"    json:"summary"`   //
	Detail    string      `orm:"detail"     json:"detail"`    // 消息详情，用户端展示使用
	CreatedAt *gtime.Time `orm:"createdAt"  json:"createdAt"` //
}
