// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// MessageRead is the golang structure for table message_read.
type MessageRead struct {
	Id        uint64      `orm:"id,primary" json:"id"`        //
	MessageId uint64      `orm:"messageId"  json:"messageId"` //
	UserId    uint64      `orm:"userId"     json:"userId"`    //
	UserType  uint        `orm:"userType"   json:"userType"`  // 1 骑手端 2  商家端
	CreatedAt *gtime.Time `orm:"createdAt"  json:"createdAt"` //
}
