// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// PackagesOrder is the golang structure for table packages_order.
type PackagesOrder struct {
	Id            uint64      `orm:"id,primary"    json:"id"`            //
	ShopId        uint        `orm:"shopId"        json:"shopId"`        //
	UserId        uint64      `orm:"userId"        json:"userId"`        // 用户ID
	No            string      `orm:"no,unique"     json:"no"`            // 订单编号
	Type          uint        `orm:"type"          json:"type"`          // 1 新签， 2 续费, 3 违约金
	PackageId     uint        `orm:"packageId"     json:"packageId"`     // 套餐ID
	Amount        float64     `orm:"amount"        json:"amount"`        // 总金额，包含押金
	Earnest       float64     `orm:"earnest"       json:"earnest"`       // 保证金
	PayType       uint        `orm:"payType"       json:"payType"`       // 1 支付宝 2 微信
	PayPlatformNo string      `orm:"payPlatformNo" json:"payPlatformNo"` // 支付平台单号
	PayAt         *gtime.Time `orm:"payAt"         json:"payAt"`         // 支付时间
	PayState      uint        `orm:"payState"      json:"payState"`      // 支付状态 1 待支付 2 已支付
	FirstUseAt    *gtime.Time `orm:"firstUseAt"    json:"firstUseAt"`    // 开始使用时间，即首次领取电池时间
	Month         int         `orm:"month"         json:"month"`         //
	CreatedAt     *gtime.Time `orm:"createdAt"     json:"createdAt"`     //
	UpdatedAt     *gtime.Time `orm:"updatedAt"     json:"updatedAt"`     //
}
