// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Payment is the golang structure for table payment.
type Payment struct {
	Id           uint64      `orm:"id,primary"   json:"id"`           //
	PayAt        *gtime.Time `orm:"payAt"        json:"payAt"`        // 支付时间
	RelationId   uint64      `orm:"relationId"   json:"relationId"`   // 关联ID
	RelationType uint        `orm:"relationType" json:"relationType"` // 关联类型:  1 购买套餐，2 续费，3 违约金
	State        uint        `orm:"state"        json:"state"`        // 0 待支付 1 已支付 2 已退款
	PayType      uint        `orm:"payType"      json:"payType"`      // 1 支付宝 2 微信
	PayNo        string      `orm:"payNo"        json:"payNo"`        // 第三方支付流水号
	Amount       float64     `orm:"amount"       json:"amount"`       // 支付金额
	No           string      `orm:"no,unique"    json:"no"`           // 支付编号
	UserId       uint64      `orm:"userId"       json:"userId"`       // 用户ID
	CreatedAt    *gtime.Time `orm:"createdAt"    json:"createdAt"`    //
	UpdatedAt    *gtime.Time `orm:"updatedAt"    json:"updatedAt"`    //
}
