// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Refund is the golang structure for table refund.
type Refund struct {
	Id               uint        `orm:"id,primary"              json:"id"`               //
	UserId           uint64      `orm:"userId"                  json:"userId"`           //
	No               string      `orm:"no,unique"               json:"no"`               // 退款编号
	RelationId       uint64      `orm:"relationId"              json:"relationId"`       //
	RelationType     uint        `orm:"relationType"            json:"relationType"`     //
	Reason           string      `orm:"reason"                  json:"reason"`           //
	Amount           float64     `orm:"amount"                  json:"amount"`           // 退款金额
	PlatformRefundNo string      `orm:"platformRefundNo,unique" json:"platformRefundNo"` // 第三方流水号
	State            uint        `orm:"state"                   json:"state"`            //
	CreatedAt        *gtime.Time `orm:"createdAt"               json:"createdAt"`        //
	UpdatedAt        *gtime.Time `orm:"updatedAt"               json:"updatedAt"`        //
}
