// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ShopManager is the golang structure for table shop_manager.
type ShopManager struct {
	Id          uint64      `orm:"id,primary"         json:"id"`          //
	Name        string      `orm:"name"               json:"name"`        // 店长姓名
	Mobile      string      `orm:"mobile"             json:"mobile"`      // 手机号码
	ShopId      uint        `orm:"shopId"             json:"shopId"`      // 店铺ID
	AccessToken string      `orm:"accessToken,unique" json:"accessToken"` //
	DeviceType  int         `orm:"deviceType"         json:"deviceType"`  // 0 未上报 1 安卓  2  iOS
	DeviceToken string      `orm:"deviceToken,unique" json:"deviceToken"` // 用户推送消息唯一ID
	DeletedAt   *gtime.Time `orm:"deletedAt"          json:"deletedAt"`   //
	CreatedAt   *gtime.Time `orm:"createdAt"          json:"createdAt"`   //
	UpdatedAt   *gtime.Time `orm:"updatedAt"          json:"updatedAt"`   //
}
