// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// ShopBatteryRecord is the golang structure for table shop_battery_record.
type ShopBatteryRecord struct {
	Id          uint64      `orm:"id,primary"  json:"id"`          //
	ShopId      uint        `orm:"shopId"      json:"shopId"`      //
	Type        uint        `orm:"type"        json:"type"`        // 1 入  2 出
	BizType     uint        `orm:"bizType"     json:"bizType"`     //
	BizId       uint64      `orm:"bizId"       json:"bizId"`       // 业务ID 为 0 即为平台调拨
	Num         uint        `orm:"num"         json:"num"`         //
	Day         int         `orm:"day"         json:"day"`         //
	UserName    string      `orm:"userName"    json:"userName"`    // 操作员 平台调拨为空
	BatteryType uint        `orm:"batteryType" json:"batteryType"` // 电池型号 60 / 72
	CreatedAt   *gtime.Time `orm:"createdAt"   json:"createdAt"`   //
}
