// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Shop is the golang structure for table shop.
type Shop struct {
	Id          uint        `orm:"id,primary"    json:"id"`          //
	State       uint        `orm:"state"         json:"state"`       // 门店状态: 0休息中 1营业中 2外出中
	ManagerName string      `orm:"managerName"   json:"managerName"` // 管理员名字
	Name        string      `orm:"name,unique"   json:"name"`        // 门店名称
	Mobile      string      `orm:"mobile,unique" json:"mobile"`      // 手机号
	ReturnAt    *gtime.Time `orm:"returnAt"      json:"returnAt"`    // 外出大致返回时间
	Lng         float64     `orm:"lng"           json:"lng"`         // 经度
	Lat         float64     `orm:"lat"           json:"lat"`         // 纬度
	Qr          string      `orm:"qr,unique"     json:"qr"`          // 二维码编号
	ProvinceId  uint        `orm:"provinceId"    json:"provinceId"`  // 省级行政编码
	CityId      uint        `orm:"cityId"        json:"cityId"`      // 市级行政编码
	DistrictId  uint        `orm:"districtId"    json:"districtId"`  // 区县行政编码
	Address     string      `orm:"address"       json:"address"`     // 详细地址
	V60         int         `orm:"v60"           json:"v60"`         // 60伏电池数量
	V72         int         `orm:"v72"           json:"v72"`         // 70伏电池数量
	CreatedAt   *gtime.Time `orm:"createdAt"     json:"createdAt"`   //
	UpdatedAt   *gtime.Time `orm:"updatedAt"     json:"updatedAt"`   //
}
