// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysRoles is the golang structure for table sys_roles.
type SysRoles struct {
	Id          uint        `orm:"id,primary"  json:"id"`          //
	Name        string      `orm:"name"        json:"name"`        // 角色名称
	Permissions string      `orm:"permissions" json:"permissions"` // 角色数组
	CreateAt    *gtime.Time `orm:"create_at"   json:"createAt"`    //
	UpdateAt    *gtime.Time `orm:"update_at"   json:"updateAt"`    //
}
