// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// SysUsers is the golang structure for table sys_users.
type SysUsers struct {
	Id           uint        `orm:"id,primary"      json:"id"`           //
	Name         string      `orm:"name"            json:"name"`         //
	Username     string      `orm:"username,unique" json:"username"`     //
	Password     string      `orm:"password"        json:"password"`     //
	Salt         string      `orm:"salt"            json:"salt"`         //
	Avatar       string      `orm:"avatar"          json:"avatar"`       //
	Roles        string      `orm:"roles"           json:"roles"`        //
	Introduction string      `orm:"introduction"    json:"introduction"` //
	AccessToken  string      `orm:"access_token"    json:"accessToken"`  //
	State        uint        `orm:"state"           json:"state"`        // 状态 1 可用，0 不可用
	DeleteAt     *gtime.Time `orm:"delete_at"       json:"deleteAt"`     // 删除时间
	CreateAt     *gtime.Time `orm:"create_at"       json:"createAt"`     //
	UpdateAt     *gtime.Time `orm:"update_at"       json:"updateAt"`     //
}
