// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// UserNote is the golang structure for table user_note.
type UserNote struct {
	Id          uint64      `orm:"id,primary"  json:"id"`          //
	UserId      uint64      `orm:"userId"      json:"userId"`      // 用户ID
	SysUserId   uint        `orm:"sysUserId"   json:"sysUserId"`   // 系统用户ID
	SysUserName string      `orm:"sysUserName" json:"sysUserName"` // 系统用户名
	Content     string      `orm:"content"     json:"content"`     // 跟进内容
	CreatedAt   *gtime.Time `orm:"createdAt"   json:"createdAt"`   //
	UpdatedAt   *gtime.Time `orm:"updatedAt"   json:"updatedAt"`   //
}
