// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id                           uint64      `orm:"id,primary"                   json:"id"`                           //
	GroupId                      uint        `orm:"groupId"                      json:"groupId"`                      // 团签用户，团体ID;  个签用户为 0
	Mobile                       string      `orm:"mobile,unique"                json:"mobile"`                       // 手机号码
	Type                         uint        `orm:"type"                         json:"type"`                         // 用户类型 	1 个签骑手 2 团签骑手 3 团签BOSS
	Qr                           string      `orm:"qr,unique"                    json:"qr"`                           // 骑手二维码数据
	RealName                     string      `orm:"realName"                     json:"realName"`                     // 真实姓名
	IdCardNo                     string      `orm:"idCardNo"                     json:"idCardNo"`                     // 身份证号码
	IdCardImg1                   string      `orm:"idCardImg1"                   json:"idCardImg1"`                   // 身份证人像面
	IdCardImg2                   string      `orm:"idCardImg2"                   json:"idCardImg2"`                   // 身份证国徽面
	IdCardImg3                   string      `orm:"idCardImg3"                   json:"idCardImg3"`                   // 手持身份证
	AuthState                    uint        `orm:"authState"                    json:"authState"`                    // 实名认证状态 0 未提交 ，1 待审核， 2 审核通过，3 审核未通过
	BatteryState                 uint        `orm:"batteryState"                 json:"batteryState"`                 // 个人用户换电状态：0 未开通，1 租借中，2 寄存中，3 已退租
	BatteryType                  uint        `orm:"batteryType"                  json:"batteryType"`                  // 套餐电池型号 60 、 72
	PackagesId                   uint        `orm:"packagesId"                   json:"packagesId"`                   // 套餐ID
	PackagesOrderId              uint64      `orm:"packagesOrderId"              json:"packagesOrderId"`              // 办理套餐订单ID
	BatteryReturnAt              *gtime.Time `orm:"batteryReturnAt"              json:"batteryReturnAt"`              // 个人用户应归还电池时间， 小于当前时间即逾期
	BatterySaveAt                *gtime.Time `orm:"batterySaveAt"                json:"batterySaveAt"`                // 个签用户电池寄存时间
	AccessToken                  string      `orm:"accessToken,unique"           json:"accessToken"`                  //
	Salt                         string      `orm:"salt"                         json:"salt"`                         //
	DeviceType                   int         `orm:"deviceType"                   json:"deviceType"`                   // 1 安卓  2  iOS
	DeviceToken                  string      `orm:"deviceToken"                  json:"deviceToken"`                  // 用户推送token
	EsignAccountId               string      `orm:"esignAccountId"               json:"esignAccountId"`               // 易签账户ID
	BizBatteryRenewalCnt         uint        `orm:"bizBatteryRenewalCnt"         json:"bizBatteryRenewalCnt"`         // 积累换次数
	BizBatteryRenewalDays        uint        `orm:"bizBatteryRenewalDays"        json:"bizBatteryRenewalDays"`        // 累计换电自然天数
	BizBatteryRenewalDaysStartAt *gtime.Time `orm:"bizBatteryRenewalDaysStartAt" json:"bizBatteryRenewalDaysStartAt"` // 需要统计使用天数的开始时间，为空则无需计算
	CreatedAt                    *gtime.Time `orm:"createdAt"                    json:"createdAt"`                    //
	UpdatedAt                    *gtime.Time `orm:"updatedAt"                    json:"updatedAt"`                    //
}
