// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
    "battery/app/dao/internal"
)

// comboDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type comboDao struct {
    *internal.ComboDao
}

var (
    // Combo is globally public accessible object for table combo operations.
    Combo comboDao
)

func init() {
    Combo = comboDao{
        internal.NewComboDao(),
    }
}

// Fill with you ideas below.
