// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// districtsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type districtsDao struct {
	*internal.DistrictsDao
}

var (
	// Districts is globally public accessible object for table districts operations.
	Districts districtsDao
)

func init() {
	Districts = districtsDao{
		internal.NewDistrictsDao(),
	}
}

// Fill with you ideas below.
