// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// groupDailyStatDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type groupDailyStatDao struct {
	*internal.GroupDailyStatDao
}

var (
	// GroupDailyStat is globally public accessible object for table group_daily_stat operations.
	GroupDailyStat groupDailyStatDao
)

func init() {
	GroupDailyStat = groupDailyStatDao{
		internal.NewGroupDailyStatDao(),
	}
}

// Fill with you ideas below.
