// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// groupDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type groupDao struct {
	*internal.GroupDao
}

var (
	// Group is globally public accessible object for table group operations.
	Group groupDao
)

func init() {
	Group = groupDao{
		internal.NewGroupDao(),
	}
}

// Fill with you ideas below.
