// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// groupSettlementDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type groupSettlementDao struct {
	*internal.GroupSettlementDao
}

var (
	// GroupSettlement is globally public accessible object for table group_settlement operations.
	GroupSettlement groupSettlementDao
)

func init() {
	GroupSettlement = groupSettlementDao{
		internal.NewGroupSettlementDao(),
	}
}

// Fill with you ideas below.
