// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// packagesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type packagesDao struct {
	*internal.PackagesDao
}

var (
	// Packages is globally public accessible object for table packages operations.
	Packages packagesDao
)

func init() {
	Packages = packagesDao{
		internal.NewPackagesDao(),
	}
}

// Fill with you ideas below.
