// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// packagesOrderDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type packagesOrderDao struct {
	*internal.PackagesOrderDao
}

var (
	// PackagesOrder is globally public accessible object for table packages_order operations.
	PackagesOrder packagesOrderDao
)

func init() {
	PackagesOrder = packagesOrderDao{
		internal.NewPackagesOrderDao(),
	}
}

// Fill with you ideas below.
