// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// paymentDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type paymentDao struct {
	*internal.PaymentDao
}

var (
	// Payment is globally public accessible object for table payment operations.
	Payment paymentDao
)

func init() {
	Payment = paymentDao{
		internal.NewPaymentDao(),
	}
}

// Fill with you ideas below.
