// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
	"crypto/md5"
	"encoding/hex"
	"math/rand"
	"strconv"
	"time"
)

// shopManagerDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type shopManagerDao struct {
	*internal.ShopManagerDao
}

var (
	// ShopManager is globally public accessible object for table shop_manager operations.
	ShopManager shopManagerDao
)

func init() {
	ShopManager = shopManagerDao{
		internal.NewShopManagerDao(),
	}
}

// GenerateAccessToken 生成accessToken
func (d *shopManagerDao) GenerateAccessToken(id uint64) string {
	r := rand.New(rand.NewSource(time.Now().Unix()))
	randBytes := make([]byte, 6)
	for i := 0; i < 6; i++ {
		randBytes[i] = byte(r.Intn(26) + 65)
	}
	m := md5.New()
	m.Write([]byte(strconv.Itoa(int(id))))
	m.Write([]byte(time.Now().String()))
	m.Write(randBytes)
	return hex.EncodeToString(m.Sum(nil))
}
