// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// signDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type signDao struct {
	*internal.SignDao
}

var (
	// Sign is globally public accessible object for table sign operations.
	Sign signDao
)

func init() {
	Sign = signDao{
		internal.NewSignDao(),
	}
}

// Fill with you ideas below.
