// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// smsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type smsDao struct {
	*internal.SmsDao
}

var (
	// Sms is globally public accessible object for table sms operations.
	Sms smsDao
)

func init() {
	Sms = smsDao{
		internal.NewSmsDao(),
	}
}

// Fill with you ideas below.
