// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// sysRolesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysRolesDao struct {
	*internal.SysRolesDao
}

var (
	// SysRoles is globally public accessible object for table sys_roles operations.
	SysRoles sysRolesDao
)

func init() {
	SysRoles = sysRolesDao{
		internal.NewSysRolesDao(),
	}
}

// Fill with you ideas below.
