// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// sysPermissionsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type sysPermissionsDao struct {
	*internal.SysPermissionsDao
}

var (
	// SysPermissions is globally public accessible object for table sys_permissions operations.
	SysPermissions sysPermissionsDao
)

func init() {
	SysPermissions = sysPermissionsDao{
		internal.NewSysPermissionsDao(),
	}
}

// Fill with you ideas below.
