// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// userBizDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userBizDao struct {
	*internal.UserBizDao
}

var (
	// UserBiz is globally public accessible object for table user_biz operations.
	UserBiz userBizDao
)

func init() {
	UserBiz = userBizDao{
		internal.NewUserBizDao(),
	}
}

// Fill with you ideas below.
