// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"battery/app/dao/internal"
)

// userNoteDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type userNoteDao struct {
	*internal.UserNoteDao
}

var (
	// UserNote is globally public accessible object for table user_note operations.
	UserNote userNoteDao
)

func init() {
	UserNote = userNoteDao{
		internal.NewUserNoteDao(),
	}
}

// Fill with you ideas below.
