// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// AdminDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type AdminDao struct {
	gmvc.M               // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB       // DB is the raw underlying database management object.
	Table   string       // Table is the table name of the DAO.
	Columns adminColumns // Columns contains all the columns of Table that for convenient usage.
}

// AdminColumns defines and stores column names for table admin.
type adminColumns struct {
	Id        string //
	CreatedAt string //
	UpdatedAt string //
	Username  string //
	Passwrod  string //
	Salt      string //
}

func NewAdminDao() *AdminDao {
	return &AdminDao{
		M:     g.DB("default").Model("admin").Safe(),
		DB:    g.DB("default"),
		Table: "admin",
		Columns: adminColumns{
			Id:        "id",
			CreatedAt: "createdAt",
			UpdatedAt: "updatedAt",
			Username:  "username",
			Passwrod:  "passwrod",
			Salt:      "salt",
		},
	}
}
