// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// DistrictsDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type DistrictsDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB           // DB is the raw underlying database management object.
	Table   string           // Table is the table name of the DAO.
	Columns districtsColumns // Columns contains all the columns of Table that for convenient usage.
}

// DistrictsColumns defines and stores column names for table districts.
type districtsColumns struct {
	Id       string //
	ParentId string //
	AdCode   string //
	CityCode string //
	Name     string //
	Level    string //
	Lng      string //
	Lat      string //
}

func NewDistrictsDao() *DistrictsDao {
	return &DistrictsDao{
		M:     g.DB("default").Model("districts").Safe(),
		DB:    g.DB("default"),
		Table: "districts",
		Columns: districtsColumns{
			Id:       "id",
			ParentId: "parentId",
			AdCode:   "adCode",
			CityCode: "cityCode",
			Name:     "name",
			Level:    "level",
			Lng:      "lng",
			Lat:      "lat",
		},
	}
}
