// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// GroupDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type GroupDao struct {
	gmvc.M               // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB       // DB is the raw underlying database management object.
	Table   string       // Table is the table name of the DAO.
	Columns groupColumns // Columns contains all the columns of Table that for convenient usage.
}

// GroupColumns defines and stores column names for table group.
type groupColumns struct {
	Id            string //
	Name          string // 名称
	ProvinceId    string // 省份ID
	CityId        string // 城市ID
	ContractFile  string // 合同文件
	ContactName   string // 联系人
	ContactMobile string // 联系电话
	CreatedAt     string //
	UpdatedAt     string //
}

func NewGroupDao() *GroupDao {
	return &GroupDao{
		M:     g.DB("default").Model("group").Safe(),
		DB:    g.DB("default"),
		Table: "group",
		Columns: groupColumns{
			Id:            "id",
			Name:          "name",
			ProvinceId:    "provinceId",
			CityId:        "cityId",
			ContractFile:  "contractFile",
			ContactName:   "contactName",
			ContactMobile: "contactMobile",
			CreatedAt:     "createdAt",
			UpdatedAt:     "updatedAt",
		},
	}
}
