// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// GroupBillDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type GroupBillDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB           // DB is the raw underlying database management object.
	Table   string           // Table is the table name of the DAO.
	Columns groupBillColumns // Columns contains all the columns of Table that for convenient usage.
}

// GroupBillColumns defines and stores column names for table group_bill.
type groupBillColumns struct {
	Id string //
}

func NewGroupBillDao() *GroupBillDao {
	return &GroupBillDao{
		M:     g.DB("default").Model("group_bill").Safe(),
		DB:    g.DB("default"),
		Table: "group_bill",
		Columns: groupBillColumns{
			Id: "id",
		},
	}
}
