// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// GroupSettlementDetailDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type GroupSettlementDetailDao struct {
	gmvc.M                               // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                       // DB is the raw underlying database management object.
	Table   string                       // Table is the table name of the DAO.
	Columns groupSettlementDetailColumns // Columns contains all the columns of Table that for convenient usage.
}

// GroupSettlementDetailColumns defines and stores column names for table group_settlement_detail.
type groupSettlementDetailColumns struct {
	Id           string //
	SettlementId string // 结算单ID
	ParentId     string // 上次结算单ID(拆分自)
	State        string // 当前状态: 0计费中 1已结算
	UserId       string // 用户ID
	GroupId      string // 团队ID
	ComboId      string // 套餐ID
	ComboOrderId string // 套餐订单ID
	Ignorance    string // 是否忽略(若同一天有多次新签退租则计为1天)
	BatteryType  string // 电池类型
	UnitPrice    string // 计费单价(每日计费)
	StartDate    string // 账单开始日期
	CancelDate   string // 退租日期
	StopDate     string // 账单结算日期
	SplitAt      string // 账单拆分日
	CreatedAt    string //
	UpdatedAt    string //
}

func NewGroupSettlementDetailDao() *GroupSettlementDetailDao {
	return &GroupSettlementDetailDao{
		M:     g.DB("default").Model("group_settlement_detail").Safe(),
		DB:    g.DB("default"),
		Table: "group_settlement_detail",
		Columns: groupSettlementDetailColumns{
			Id:           "id",
			SettlementId: "settlementId",
			ParentId:     "parentId",
			State:        "state",
			UserId:       "userId",
			GroupId:      "groupId",
			ComboId:      "comboId",
			ComboOrderId: "comboOrderId",
			Ignorance:    "ignorance",
			BatteryType:  "batteryType",
			UnitPrice:    "unitPrice",
			StartDate:    "startDate",
			CancelDate:   "cancelDate",
			StopDate:     "stopDate",
			SplitAt:      "splitAt",
			CreatedAt:    "createdAt",
			UpdatedAt:    "updatedAt",
		},
	}
}
