// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// MessageReadDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type MessageReadDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns messageReadColumns // Columns contains all the columns of Table that for convenient usage.
}

// MessageReadColumns defines and stores column names for table message_read.
type messageReadColumns struct {
	Id        string //
	MessageId string //
	UserId    string //
	UserType  string // 1骑手端 2商家端
	CreatedAt string //
}

func NewMessageReadDao() *MessageReadDao {
	return &MessageReadDao{
		M:     g.DB("default").Model("message_read").Safe(),
		DB:    g.DB("default"),
		Table: "message_read",
		Columns: messageReadColumns{
			Id:        "id",
			MessageId: "messageId",
			UserId:    "userId",
			UserType:  "userType",
			CreatedAt: "createdAt",
		},
	}
}
