// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// PackagesOrderDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type PackagesOrderDao struct {
	gmvc.M                       // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB               // DB is the raw underlying database management object.
	Table   string               // Table is the table name of the DAO.
	Columns packagesOrderColumns // Columns contains all the columns of Table that for convenient usage.
}

// PackagesOrderColumns defines and stores column names for table packages_order.
type packagesOrderColumns struct {
	Id            string //
	ParentId      string // 关联订单ID(续签或违约)
	CityId        string // 城市ID
	ShopId        string //
	UserId        string // 用户ID
	No            string // 订单编号
	Type          string // 1 新签， 2 续费, 3 违约金
	PackageId     string // 套餐ID
	Amount        string // 总金额，包含押金
	Earnest       string // 保证金
	PayType       string // 1 支付宝 2 微信
	PayPlatformNo string // 支付平台单号
	PayAt         string // 支付时间
	PayState      string // 支付状态 1 待支付 2 已支付
	FirstUseAt    string // 开始使用时间，即首次领取电池时间
	Month         string //
	CreatedAt     string //
	UpdatedAt     string //
}

func NewPackagesOrderDao() *PackagesOrderDao {
	return &PackagesOrderDao{
		M:     g.DB("default").Model("packages_order").Safe(),
		DB:    g.DB("default"),
		Table: "packages_order",
		Columns: packagesOrderColumns{
			Id:            "id",
			ParentId:      "parentId",
			CityId:        "cityId",
			ShopId:        "shopId",
			UserId:        "userId",
			No:            "no",
			Type:          "type",
			PackageId:     "packageId",
			Amount:        "amount",
			Earnest:       "earnest",
			PayType:       "payType",
			PayPlatformNo: "payPlatformNo",
			PayAt:         "payAt",
			PayState:      "payState",
			FirstUseAt:    "firstUseAt",
			Month:         "month",
			CreatedAt:     "createdAt",
			UpdatedAt:     "updatedAt",
		},
	}
}
