// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// RefundDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type RefundDao struct {
	gmvc.M                // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB        // DB is the raw underlying database management object.
	Table   string        // Table is the table name of the DAO.
	Columns refundColumns // Columns contains all the columns of Table that for convenient usage.
}

// RefundColumns defines and stores column names for table refund.
type refundColumns struct {
	Id               string //
	UserId           string //
	No               string // 退款编号
	RelationId       string //
	RelationType     string //
	Amount           string // 退款金额
	PlatformRefundNo string // 第三方流水号
	State            string //
	CreatedAt        string //
	UpdatedAt        string //
}

func NewRefundDao() *RefundDao {
	return &RefundDao{
		M:     g.DB("default").Model("refund").Safe(),
		DB:    g.DB("default"),
		Table: "refund",
		Columns: refundColumns{
			Id:               "id",
			UserId:           "userId",
			No:               "no",
			RelationId:       "relationId",
			RelationType:     "relationType",
			Amount:           "amount",
			PlatformRefundNo: "platformRefundNo",
			State:            "state",
			CreatedAt:        "createdAt",
			UpdatedAt:        "updatedAt",
		},
	}
}
