// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ShopDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ShopDao struct {
	gmvc.M              // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB      // DB is the raw underlying database management object.
	Table   string      // Table is the table name of the DAO.
	Columns shopColumns // Columns contains all the columns of Table that for convenient usage.
}

// ShopColumns defines and stores column names for table shop.
type shopColumns struct {
	Id          string //
	State       string // 门店状态: 0休息中 1营业中 2外出中
	ManagerName string // 管理员名字
	Name        string // 门店名称
	Mobile      string // 手机号
	ReturnAt    string // 外出大致返回时间
	Lng         string // 经度
	Lat         string // 纬度
	Qr          string // 二维码编号
	ProvinceId  string // 省级行政编码
	CityId      string // 市级行政编码
	DistrictId  string // 区县行政编码
	Address     string // 详细地址
	V60         string // 60伏电池数量
	V72         string // 70伏电池数量
	CreatedAt   string //
	UpdatedAt   string //
}

func NewShopDao() *ShopDao {
	return &ShopDao{
		M:     g.DB("default").Model("shop").Safe(),
		DB:    g.DB("default"),
		Table: "shop",
		Columns: shopColumns{
			Id:          "id",
			State:       "state",
			ManagerName: "managerName",
			Name:        "name",
			Mobile:      "mobile",
			ReturnAt:    "returnAt",
			Lng:         "lng",
			Lat:         "lat",
			Qr:          "qr",
			ProvinceId:  "provinceId",
			CityId:      "cityId",
			DistrictId:  "districtId",
			Address:     "address",
			V60:         "v60",
			V72:         "v72",
			CreatedAt:   "createdAt",
			UpdatedAt:   "updatedAt",
		},
	}
}
