// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
    "github.com/gogf/gf/database/gdb"
    "github.com/gogf/gf/frame/g"
    "github.com/gogf/gf/frame/gmvc"
)

// ShopDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ShopDao struct {
    gmvc.M              // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
    DB      gdb.DB      // DB is the raw underlying database management object.
    Table   string      // Table is the table name of the DAO.
    Columns shopColumns // Columns contains all the columns of Table that for convenient usage.
}

// ShopColumns defines and stores column names for table shop.
type shopColumns struct {
    Id              string //
    State           string // 门店状态 0 休息总，1 营业中，2 外出中
    ManagerName     string //
    Name            string // 门店名称
    Mobile          string // 手机号
    ReturnAt        string // 外出大致返回时间
    BatteryOutCnt60 string // 60伏电池出库数量
    BatteryInCnt60  string // 60伏电池入库数量
    BatteryInCnt72  string // 72伏电池入库数量
    BatteryOutCnt72 string // 72伏电池出库数量
    ChargerInCnt    string // 充电器入库数量
    ChargerOutCnt   string // 充电器出库数量
    BatteryCnt72    string // 72伏电池数量
    BatteryCnt60    string // 60伏电池数量
    ChargerCnt      string // 充电器数量
    Lng             string // 经度
    Lat             string // 纬度
    Qr              string // 二维码编号
    ProvinceId      string // 省级行政编码
    CityId          string // 市级行政编码
    DistrictId      string // 区县行政编码
    Address         string // 详细地址
    CreatedAt       string //
    UpdatedAt       string //
}

func NewShopDao() *ShopDao {
    return &ShopDao{
        M:     g.DB("default").Model("shop").Safe(),
        DB:    g.DB("default"),
        Table: "shop",
        Columns: shopColumns{
            Id:              "id",
            State:           "state",
            ManagerName:     "managerName",
            Name:            "name",
            Mobile:          "mobile",
            ReturnAt:        "returnAt",
            BatteryOutCnt60: "batteryOutCnt60",
            BatteryInCnt60:  "batteryInCnt60",
            BatteryInCnt72:  "batteryInCnt72",
            BatteryOutCnt72: "batteryOutCnt72",
            ChargerInCnt:    "chargerInCnt",
            ChargerOutCnt:   "chargerOutCnt",
            BatteryCnt72:    "batteryCnt72",
            BatteryCnt60:    "batteryCnt60",
            ChargerCnt:      "chargerCnt",
            Lng:             "lng",
            Lat:             "lat",
            Qr:              "qr",
            ProvinceId:      "provinceId",
            CityId:          "cityId",
            DistrictId:      "districtId",
            Address:         "address",
            CreatedAt:       "createdAt",
            UpdatedAt:       "updatedAt",
        },
    }
}
