// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// ShopManagerDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type ShopManagerDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB             // DB is the raw underlying database management object.
	Table   string             // Table is the table name of the DAO.
	Columns shopManagerColumns // Columns contains all the columns of Table that for convenient usage.
}

// ShopManagerColumns defines and stores column names for table shop_manager.
type shopManagerColumns struct {
	Id          string //
	ShopId      string // 门店ID
	Name        string // 管理员
	Mobile      string // 手机号码
	AccessToken string //
	DeviceType  string // 设备类型: 0未上报 1安卓 2iOS
	DeviceToken string // 用户推送token
	DeletedAt   string //
	CreatedAt   string //
	UpdatedAt   string //
}

func NewShopManagerDao() *ShopManagerDao {
	return &ShopManagerDao{
		M:     g.DB("default").Model("shop_manager").Safe(),
		DB:    g.DB("default"),
		Table: "shop_manager",
		Columns: shopManagerColumns{
			Id:          "id",
			ShopId:      "shopId",
			Name:        "name",
			Mobile:      "mobile",
			AccessToken: "accessToken",
			DeviceType:  "deviceType",
			DeviceToken: "deviceToken",
			DeletedAt:   "deletedAt",
			CreatedAt:   "createdAt",
			UpdatedAt:   "updatedAt",
		},
	}
}
