// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SmsDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SmsDao struct {
	gmvc.M             // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB     // DB is the raw underlying database management object.
	Table   string     // Table is the table name of the DAO.
	Columns smsColumns // Columns contains all the columns of Table that for convenient usage.
}

// SmsColumns defines and stores column names for table sms.
type smsColumns struct {
	Id        string //
	Mobile    string //
	Code      string // 验证码
	CreatedAt string //
}

func NewSmsDao() *SmsDao {
	return &SmsDao{
		M:     g.DB("default").Model("sms").Safe(),
		DB:    g.DB("default"),
		Table: "sms",
		Columns: smsColumns{
			Id:        "id",
			Mobile:    "mobile",
			Code:      "code",
			CreatedAt: "createdAt",
		},
	}
}
