// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysPermissionsDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysPermissionsDao struct {
	gmvc.M                        // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB                // DB is the raw underlying database management object.
	Table   string                // Table is the table name of the DAO.
	Columns sysPermissionsColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysPermissionsColumns defines and stores column names for table sys_permissions.
type sysPermissionsColumns struct {
	Id       string //
	ParentId string // 上级权限ID
	Method   string // HTTP请求方法 大写
	Path     string // 访问资源路径
	Name     string //
	Vtype    string // 前端路由类型  1 菜单 2 按钮
	Vpath    string // Vue 路由
	CreateAt string //
	UpdateAt string //
}

func NewSysPermissionsDao() *SysPermissionsDao {
	return &SysPermissionsDao{
		M:     g.DB("default").Model("sys_permissions").Safe(),
		DB:    g.DB("default"),
		Table: "sys_permissions",
		Columns: sysPermissionsColumns{
			Id:       "id",
			ParentId: "parent_id",
			Method:   "method",
			Path:     "path",
			Name:     "name",
			Vtype:    "vtype",
			Vpath:    "vpath",
			CreateAt: "create_at",
			UpdateAt: "update_at",
		},
	}
}
