// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysRolesDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysRolesDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns sysRolesColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysRolesColumns defines and stores column names for table sys_roles.
type sysRolesColumns struct {
	Id          string //
	Name        string // 角色名称
	Permissions string // 角色数组
	CreateAt    string //
	UpdateAt    string //
}

func NewSysRolesDao() *SysRolesDao {
	return &SysRolesDao{
		M:     g.DB("default").Model("sys_roles").Safe(),
		DB:    g.DB("default"),
		Table: "sys_roles",
		Columns: sysRolesColumns{
			Id:          "id",
			Name:        "name",
			Permissions: "permissions",
			CreateAt:    "create_at",
			UpdateAt:    "update_at",
		},
	}
}
