// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SysUsersDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type SysUsersDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns sysUsersColumns // Columns contains all the columns of Table that for convenient usage.
}

// SysUsersColumns defines and stores column names for table sys_users.
type sysUsersColumns struct {
	Id           string //
	Name         string //
	Username     string //
	Password     string //
	Salt         string //
	Avatar       string //
	Roles        string //
	Introduction string //
	AccessToken  string //
	State        string // 状态 1 可用，0 不可用
	DeleteAt     string // 删除时间
	CreateAt     string //
	UpdateAt     string //
}

func NewSysUsersDao() *SysUsersDao {
	return &SysUsersDao{
		M:     g.DB("default").Model("sys_users").Safe(),
		DB:    g.DB("default"),
		Table: "sys_users",
		Columns: sysUsersColumns{
			Id:           "id",
			Name:         "name",
			Username:     "username",
			Password:     "password",
			Salt:         "salt",
			Avatar:       "avatar",
			Roles:        "roles",
			Introduction: "introduction",
			AccessToken:  "access_token",
			State:        "state",
			DeleteAt:     "delete_at",
			CreateAt:     "create_at",
			UpdateAt:     "update_at",
		},
	}
}
