// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserBizDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserBizDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns userBizColumns // Columns contains all the columns of Table that for convenient usage.
}

// UserBizColumns defines and stores column names for table user_biz.
type userBizColumns struct {
	Id           string //
	CityId       string //
	ShopId       string // 店铺ID
	UserId       string //
	GoroupId     string // 团体ID
	GoroupUserId string //
	Type         string // 业务类型:  1 新签， 2 换电，3 寄存，4 退租
	PackagesId   string // 个签 套餐ID
	BatteryType  string // 电池型号 60 / 72
	CreatedAt    string // 扫码时间
	UpdatedAt    string //
}

func NewUserBizDao() *UserBizDao {
	return &UserBizDao{
		M:     g.DB("default").Model("user_biz").Safe(),
		DB:    g.DB("default"),
		Table: "user_biz",
		Columns: userBizColumns{
			Id:           "id",
			CityId:       "cityId",
			ShopId:       "shopId",
			UserId:       "userId",
			GoroupId:     "goroupId",
			GoroupUserId: "goroupUserId",
			Type:         "type",
			PackagesId:   "packagesId",
			BatteryType:  "batteryType",
			CreatedAt:    "createdAt",
			UpdatedAt:    "updatedAt",
		},
	}
}
