// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserNoteDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserNoteDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB          // DB is the raw underlying database management object.
	Table   string          // Table is the table name of the DAO.
	Columns userNoteColumns // Columns contains all the columns of Table that for convenient usage.
}

// UserNoteColumns defines and stores column names for table user_note.
type userNoteColumns struct {
	Id          string //
	UserId      string // 用户ID
	SysUserId   string // 系统用户ID
	SysUserName string // 系统用户名
	Content     string // 跟进内容
	CreatedAt   string //
	UpdatedAt   string //
}

func NewUserNoteDao() *UserNoteDao {
	return &UserNoteDao{
		M:     g.DB("default").Model("user_note").Safe(),
		DB:    g.DB("default"),
		Table: "user_note",
		Columns: userNoteColumns{
			Id:          "id",
			UserId:      "userId",
			SysUserId:   "sysUserId",
			SysUserName: "sysUserName",
			Content:     "content",
			CreatedAt:   "createdAt",
			UpdatedAt:   "updatedAt",
		},
	}
}
