// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserBizDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type UserBizDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB         // DB is the raw underlying database management object.
	Table   string         // Table is the table name of the DAO.
	Columns userBizColumns // Columns contains all the columns of Table that for convenient usage.
}

// UserBizColumns defines and stores column names for table user_biz.
type userBizColumns struct {
	Id           string //
	UserId       string // 用户ID
	ComboId      string // 套餐ID
	CityId       string // 城市ID
	ShopId       string // 门店ID
	GoroupId     string // 团签ID
	GoroupUserId string // 团签用户ID
	Type         string // 业务类型: 1新签 2换电 3寄存 4恢复计费 5退租
	BatteryType  string // 电池型号
	CreatedAt    string // 扫码时间
	UpdatedAt    string //
}

func NewUserBizDao() *UserBizDao {
	return &UserBizDao{
		M:     g.DB("default").Model("user_biz").Safe(),
		DB:    g.DB("default"),
		Table: "user_biz",
		Columns: userBizColumns{
			Id:           "id",
			UserId:       "userId",
			ComboId:      "comboId",
			CityId:       "cityId",
			ShopId:       "shopId",
			GoroupId:     "goroupId",
			GoroupUserId: "goroupUserId",
			Type:         "type",
			BatteryType:  "batteryType",
			CreatedAt:    "createdAt",
			UpdatedAt:    "updatedAt",
		},
	}
}
